# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\resources\watcher_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import resources
from PyQt5 import QtCore, QtGui, QtWidgets


class WatcherMainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 600)
        MainWindow.setStyleSheet("background-color: rgb(11, 175, 208);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainPnl = QtWidgets.QFrame(self.centralwidget)
        self.mainPnl.setGeometry(QtCore.QRect(33, 46, 433, 508))
        self.mainPnl.setStyleSheet("background-color: rgb(250, 254, 255);\n"
                                   "border-radius: 20;")
        self.mainPnl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainPnl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainPnl.setLineWidth(3)
        self.mainPnl.setMidLineWidth(3)
        self.mainPnl.setObjectName("mainPnl")
        self.btnInit = QtWidgets.QPushButton(self.mainPnl)
        self.btnInit.setGeometry(QtCore.QRect(116, 410, 200, 50))
        self.btnInit.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnInit.setFont(font)
        self.btnInit.setStyleSheet("background-color: rgb(102, 105, 197);\n"
                                   "border-radius: 8;\n"
                                   "color: rgb(255, 255, 255);")
        self.btnInit.setFlat(False)
        self.btnInit.setObjectName("btnInit")
        self.cbxComponent = QtWidgets.QComboBox(self.mainPnl)
        self.cbxComponent.setGeometry(QtCore.QRect(54, 330, 323, 48))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cbxComponent.setFont(font)
        self.cbxComponent.setStyleSheet("background-color: rgb(235, 235, 235);\n"
                                        "color: rgb(68, 68, 68);\n"
                                        "border-radius: 8;")
        self.cbxComponent.setFrame(True)
        self.cbxComponent.setObjectName("cbxComponent")
        self.lblCmbComponent = QtWidgets.QLabel(self.mainPnl)
        self.lblCmbComponent.setGeometry(QtCore.QRect(54, 300, 325, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lblCmbComponent.setFont(font)
        self.lblCmbComponent.setObjectName("lblCmbComponent")
        self.lblWelcome = QtWidgets.QLabel(self.mainPnl)
        self.lblWelcome.setGeometry(QtCore.QRect(54, 190, 325, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(30)
        self.lblWelcome.setFont(font)
        self.lblWelcome.setObjectName("lblWelcome")
        self.lblStudentName = QtWidgets.QLabel(self.mainPnl)
        self.lblStudentName.setGeometry(QtCore.QRect(54, 230, 325, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(30)
        self.lblStudentName.setFont(font)
        self.lblStudentName.setObjectName("lblStudentName")
        self.lblLogo = QtWidgets.QLabel(self.mainPnl)
        self.lblLogo.setGeometry(QtCore.QRect(54, 58, 325, 111))
        self.lblLogo.setStyleSheet(
            "image: url(:/logo/img/StudentOwlLogoRight.png);")
        self.lblLogo.setText("")
        self.lblLogo.setObjectName("lblLogo")
        self.lblLogo.raise_()
        self.btnInit.raise_()
        self.cbxComponent.raise_()
        self.lblCmbComponent.raise_()
        self.lblWelcome.raise_()
        self.lblStudentName.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "StudentOwl - Monitoreo"))
        self.btnInit.setText(_translate("MainWindow", "Iniciar"))
        self.lblCmbComponent.setText(_translate(
            "MainWindow", "Seleccione el componente académico:"))
        self.lblWelcome.setText(_translate("MainWindow", "Bienvenido"))
        self.lblStudentName.setText(_translate("MainWindow", "estudiante"))
