@ECHO OFF
:: This batch file init the Step 1 for StudentOwl - Monitoreo
TITLE StudentOwl-Monitoreo Step 1
ECHO Please wait...
ECHO Start Step 1
START ../programs/Step-1.exe
ECHO Complete...
ECHO Exit...